apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  type: NodePort
  selector:
    app: quarkus-demo
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
