name: 🚀 Despliegue a MicroK8s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar a MicroK8s
    runs-on: [self-hosted, linux]

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🔧 Exportar /snap/bin al PATH
        run: |
          echo "/snap/bin" >> $GITHUB_PATH
          export PATH=$PATH:/snap/bin

      - name: 🟢 Verificar que MicroK8s está listo
        run: |
          sudo microk8s status --wait-ready

      - name: 🚢 Aplicar manifiesto Deployment
        run: |
          sudo microk8s kubectl apply --validate=false -f k8s/deployment.yaml

      - name: 🚢 Aplicar manifiesto Service
        run: |
          sudo microk8s kubectl apply --validate=false -f k8s/service.yaml

      - name: ✅ Verificar recursos desplegados
        run: |
          sudo microk8s kubectl get all -n default
